name: Deploy to GitHub Pages

# Kích hoạt action này mỗi khi có code mới được đẩy lên nhánh main
on:
  push:
    branches:
      - main # Nếu nhánh chính của bạn tên là master, hãy đổi chữ main thành master

# Phân quyền cho GitHub Actions được phép đọc code và đẩy trang web lên Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Hủy các bản build cũ nếu có bản build mới đang chạy
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tải mã nguồn về máy chủ GitHub
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cài đặt các gói thư viện (Dependencies)
        run: npm install

      - name: Chạy lệnh Build ra trang web tĩnh
        # Khai báo các biến môi trường để Vite lấy từ Secrets ghép vào code khi build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_DATABASE_ID: ${{ secrets.VITE_FIREBASE_DATABASE_ID }}
        run: npm run build

      - name: Cài đặt Pages
        uses: actions/configure-pages@v4

      - name: Đóng gói thư mục dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vì Vite luôn build code ra thư mục tên là "dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Đẩy lên GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
